### ISSUE TITLE
is-codelist option shown for each root PSM class

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/model-driven-data#103]
If I understand it correctly, is-codelist option is shown only for classes which are returned with is-codelist annotation by the input SPARQL queries. If so, there is a bug because each root PSM class has this option shown in the dialog for its editation.

**Comment by sstenchlak** [comment]
The behavior is correct, under my current understanding. Right now, the is-codelist option is shown for **every class** having a PIM interpretation and should be correctly set according to CIM. For example, "Palivo jako položka číselníku" has checked that option because it is a code list no matter if it is a root or not. (there is still a "+" icon, which is a bug)

Is codelist is the property of PIM, where there is no concept of a root. If you hide the option for PSM root classes and treat them always as non-codelist, wouldn't that bring an inconsistency, that sometimes it is and sometimes it is not a code list?

**Comment by martinnec** [comment]
Yes, you are right. This is correct behavior.
